grafana:
  adminPassword: "admin"
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki:3100
      access: proxy
      isDefault: false
    - name: Tempo
      type: tempo
      url: http://tempo:3200
      access: proxy
      isDefault: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    enableRemoteWriteReceiver: true

alertmanager:
  enabled: true  
  alertmanagerSpec:
    secrets:
      - telegram-bot-token
  config:
    global:
      resolve_timeout: 5m
      http_config:
        proxy_url: 'proxy_url'
    route:
      group_by: ['namespace', 'alertname', 'service']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      receiver: 'telegram-oncall' 
      routes:
        - matchers:
            - severity="critical"
          receiver: 'telegram-oncall' 
    inhibit_rules:
      - source_matchers:
          - severity="critical"
        target_matchers:
          - severity="warning"
        equal: ['namespace', 'service']
    receivers:
      - name: 'blackhole'
      - name: 'telegram-oncall'
        telegram_configs:
          - bot_token_file: '/etc/alertmanager/secrets/telegram-bot-token/token'
            chat_id: 759850364
            parse_mode: 'HTML'
            message: |-
              {{ if eq .Status "firing" }}🔥 <b>СБОЙ (FIRING)</b> 🔥{{ else }}✅ <b>ВОССТАНОВЛЕНО (RESOLVED)</b> ✅{{ end }}
              <b>Alert:</b> {{ .GroupLabels.alertname }}
              <b>Service:</b> {{ .GroupLabels.service }}
              <b>Подробности:</b>
              {{ range .Alerts }}
              • {{ .Annotations.summary }}
              {{ end }}

additionalPrometheusRulesMap:
  online-boutique-rules:
    groups:
      - name: spanmetrics-alerts
        rules:
          # 1. Критический алерт: Доля ошибок больше 5%
          - alert: HighErrorRate
            expr: |
              sum by (span_name) (rate(traces_span_metrics_calls_total{status_code="STATUS_CODE_ERROR"}[3m])) 
              / 
              sum by (span_name) (rate(traces_span_metrics_calls_total[3m])) > 0.05
            for: 1m
            labels:
              severity: critical
              service: frontend
            annotations:
              summary: "Всплеск ошибок на эндпоинте {{ $labels.span_name }}"
              description: "Уровень ошибок превысил 5% за последние 3 минуты."

          # 2. Предупреждение: 95% пользователей ждут ответа дольше 1 секунды (1000 мс)
          - alert: HighLatencyP95
            expr: |
              histogram_quantile(0.95, sum by (le, span_name) (rate(traces_span_metrics_duration_milliseconds_bucket[3m]))) > 1000
            for: 1m
            labels:
              severity: warning
              service: frontend
            annotations:
              summary: "Деградация скорости на {{ $labels.span_name }}"
              description: "P95 Latency превысил 1000ms за последние 3 минуты."
