loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  auth_enabled: false
# Отключаем микросервисный режим, запускаем монолит
deploymentMode: SingleBinary
singleBinary:
  replicas: 1
# Отключаем встроенные агенты сбора (мы будем использовать Alloy)
promtail:
  enabled: false

