alloy:
  configMap:
    content: |
      // --- 1. ЛОГИ (Loki) ---
      discovery.kubernetes "pods" {
        role = "pod"
      }

      discovery.relabel "pods" {
        targets = discovery.kubernetes.pods.targets
        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          action = "keep"
          regex = "demo-app"
        }
        rule {
          source_labels = ["__meta_kubernetes_pod_label_app"]
          action = "replace"
          target_label = "app"
        }
      }

      loki.source.kubernetes "local_pods" {
        targets    = discovery.relabel.pods.output
        forward_to = [loki.write.local.receiver]
      }

      loki.write "local" {
        endpoint {
          url = "http://loki:3100/loki/api/v1/push"
        }
      }

      // --- 2. ПРИЕМНИК OTLP ---
      otelcol.receiver.otlp "default" {
        grpc { endpoint = "0.0.0.0:4317" }
        http { endpoint = "0.0.0.0:4318" }
        
        output {
          metrics = [otelcol.exporter.prometheus.default.input]
          traces  = [
            otelcol.exporter.otlp.tempo.input,
            otelcol.connector.spanmetrics.default.input,
          ]
        }
      }

      // --- 3. ГЕНЕРАТОР МЕТРИК ИЗ ТРЕЙСОВ ---
      otelcol.connector.spanmetrics "default" {
        histogram {
          explicit {}
        }
        output {
          metrics = [otelcol.exporter.prometheus.default.input]
        }
      }

      // --- 4. ЭКСПОРТЕРЫ ---
      otelcol.exporter.prometheus "default" {
        forward_to = [prometheus.remote_write.local.receiver]
      }

      prometheus.remote_write "local" {
        endpoint {
          url = "http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
        }
      }

      otelcol.exporter.otlp "tempo" {
        client {
          endpoint = "tempo.monitoring.svc.cluster.local:4317"
          tls {
            insecure             = true
            insecure_skip_verify = true
          }
        }
      }
